{{- if and .Values.admin.autoscaling.enabled .Values.admin.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hoppscotch.admin" . }}
  labels: {{- include "common.labels.commonLabels" ( dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: admin
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hoppscotch.admin" . }}
  minReplicas: {{ .Values.admin.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.admin.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.admin.autoscaling.targetCPUPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.admin.autoscaling.targetCPUPercentage }}
    {{- end }}
    {{- if .Values.admin.autoscaling.targetMemoryPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.admin.autoscaling.targetmemoryPercentage }}
    {{- end }}
{{- end }}