{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoppscotch.admin" . }}
  labels: {{- include "common.labels.commonLabels" ( dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: admin
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.admin.service.type }}
  {{- if and .Values.admin.service.clusterIP (eq .Values.admin.service.type "ClusterIP") }}
  clusterIP: {{ .Values.admin.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.admin.containerPorts.server }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "common.labels.selectorLabels" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: admin
{{- end }}