{{- if .Values.backend.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hoppscotch.backend" . }}-migrate-{{ now | date "2006-01-02-154530" }}
  labels: {{- include "common.labels.commonLabels" ( dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: backend
    annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: {{ include "hoppscotch.getImage" (dict "value" .Values.backend.image "context" $)}}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running migrations";
              pnpx prisma migrate deploy;
          env: {{- (include "hoppscotch.extraEnv" (deepCopy .Values.global.extraEnv | merge .Values.backend.extraEnv)) | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "hoppscotch.envvars" . }}
            - secretRef:
                name: {{ include "hoppscotch.envvars" . }}
            - secretref:
                name: {{ printf "%s-proxy" (include "common.names.fullname" .) }}
      restartPolicy: Never
  backoffLimit: 5
{{- end }}