{{- if and .Values.frontend.autoscaling.enabled .Values.frontend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hoppscotch.frontend" . }}
  labels: {{- include "common.labels.commonLabels" ( dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hoppscotch.frontend" . }}
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.frontend.autoscaling.targetCPUPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          averageValue: {{ .Values.frontend.autoscaling.targetCPUPercentage }}
          type: Utilization
    {{- end }}
    {{- if .Values.frontend.autoscaling.targetMemoryPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          averageValue: {{ .Values.frontend.autoscaling.targetMemoryPercentage }}
          type: Utilization
    {{- end }}
{{- end }}