{{- if .Values.ingress.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoppscotch.basicAuth" .}}
  labels:
    labels: {{- include "common.labels.commonLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: Opaque
data:
  auth: |
{{- range .Values.ingress.auth }}
    {{ .username }}:{{ printf "%s-%s" .username .password | b64enc }}
{{- end }}
{{- end }}