{{- if .Values.ingress.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoppscotch.basicAuth" .}}
  labels:
    labels: {{- include "common.labels.commonLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: Opaque
data:
  auth: {{ include "hoppscotch.basicAuth.generateHtpasswd" . | b64enc }}
{{- end }}