{{- if and .Values.ingress.enabled ( or .Values.admin.enabled .Values.frontend.enabled .Values.proxy.enabled ) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.ingress.auth }}
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: {{ include "hoppscotch.basicAuth" . }}
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ include "common.names.fullname" . }}-tls
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
        {{- if .Values.frontend.enabled }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.frontend" . }}
              port:
                number: {{ .Values.frontend.containerPorts.server }}
        {{- end }}
        {{- if .Values.proxy.enabled}}
        - path: /proxy
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.proxy" . }}
              port:
                number: {{ .Values.proxy.containerPorts.server }}
        {{- end }}
{{- end }}
{{- if and .Values.ingress.enabled .Values.backend.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ include "common.names.fullname" . }}-tls
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
        - path: /backend(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ include "hoppscotch.backend" . }}
              port:
                number: {{ .Values.backend.containerPorts.server }}
{{- end }}
{{- if and .Values.ingress.enabled .Values.admin.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ include "common.names.fullname" . }}-tls
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
        - path: /admin
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.admin" . }}
              port:
                number: {{ .Values.admin.containerPorts.server }}
{{- end }}
