{{- if and .Values.ingress.enabled ( or .Values.admin.enabled .Values.backend.enabled .Values.frontend.enabled .Values.proxy.enabled ) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.hostname }}
        secretName: {{ include "common.names.fullname" . }}-tls
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
        {{- if .Values.admin.enabled }}
        - path: /admin
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.admin" . }}
              port:
                number: {{ .Values.admin.containerPorts.server }}
        {{- end }}
        {{- if .Values.backend.enabled }}
        - path: /backend
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.backend" . }}
              port:
                number: {{ .Values.backend.containerPorts.server }}
        {{- end }}
        {{- if .Values.frontend.enabled }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.frontend" . }}
              port:
                number: {{ .Values.frontend.containerPorts.server }}
        {{- end }}
        {{- if .Values.proxy.enabled}}
        - path: /proxy
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.proxy" . }}
              port:
                number: {{ .Values.proxy.containerPorts.server }}
        {{- end }}
{{- end }}
