{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
        - path: /admin
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.admin" . }}
              port:
                number: {{ .Values.admin.containerPorts.server }}
        - path: /backend
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.backend" . }}
              port:
                number: {{ .Values.backend.containerPorts.server }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.frontend" . }}
              port:
                number: {{ .Values.frontend.containerPorts.server }}
{{- end }}
