{{- if and .Values.ingress.enabled ( or .Values.admin.enabled .Values.backend.enabled .Values.frontend.enabled ) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
        {{- if .Values.admin.enabled }}
        - path: /admin
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.admin" . }}
              port:
                number: {{ .Values.admin.containerPorts.server }}
        {{- end }}
        {{- if .Values.backend.enabled }}
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.backend" . }}
              port:
                number: {{ .Values.backend.containerPorts.server }}
        {{- end }}
        {{- if .Values.frontend.enabled }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "hoppscotch.frontend" . }}
              port:
                number: {{ .Values.frontend.containerPorts.server }}
        - path: /proxy
          pathType: Prefix
          backend:
            service:
              name: dev-hoppscotch-proxy
              port:
                number: 9159
        {{- end }}
{{- end }}
