{{- if .Values.proxyEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-proxy
  labels: {{- include "common.labels.commonLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "2"
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- range $key, $value := .Values.proxyEnv }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}