---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.authSecretName" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
data:
  username: {{ .Values.global.database.username | b64enc }}
  password: {{ .Values.global.database.password | b64enc }}
type: kubernetes.io/basic-auth
